"use client"
import Header from '@/components/header/Header'
import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './provider'


const metadata: Metadata = {
  title: 'GPOL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Providers>
          {children}
        </Providers>
        </body>
    </html>
  )
}
